### ISSUE TITLE
Interpretation of D-Score in relation to attribute order

### ISSUE THREAD

**Issue by TorstenMH** [ianhussey/IAT#5]
Thanks for the great psychopy IAT code.
I have one problem that I cannot find any information on. How is the D-score interpreted in relation to the order of the attributes entered in the respective file. So, does a larger D-score imply a positive relation between the first category and the first attribute (and negative relation between first category and second attribute)? If I'm not completely misunderstanding something, then I think that this information should be given in the README.md/pdf files.
Thanks,
Torsten

**Comment by ianhussey** [comment]
I added such an interpretation to the readme file:

Positive D1 scores refer to faster responding on the block where response mappings are shared between trial types 1 & 3 and 2 & 4 (e.g., flowers-positive/insects-negative) than the block where response mappings are shared between trial types 1 & 4 and 2 & 3 (e.g., flowers-negative/insects-positive).
